Repository Voog/design-sapporo, pull requests merged in 2018-04, with the labels that each got.

#205 Product list and arrow back
  components/menu-level-1-link.tpl
  components/template-variables.tpl
  package-lock.json
  package.json
  yarn.lock
Labels: needs review

#197 "Search not found" translation to current viewing language.
  components/template-javascripts.tpl
  components/template-tools.tpl
  javascripts/main.js
  javascripts/main.min.js
  layouts/product.tpl
  sources/javascripts/concat/base.js
Labels: bug, needs review

#206 Display Product related items in editmode if parent page is hidden.
  components/menu-breadcrumbs-buttons-loop.tpl
  components/menu-breadcrumbs.tpl
  components/product-list-loop.tpl
  layouts/product_list.tpl
Labels: bug, tested (needs work)
