Repository Voog/design-sapporo, pull requests merged in 2018-05, with the labels that each got.

#212 Remove from menu-main level_1 title.
  components/menu-level-2.tpl
  components/template-cs-style-rules.tpl
  stylesheets/main.css
Labels: bug, important

#208 Fix blog tags & if statement.
  components/blog-list-tags.tpl
Labels: bug, needs testing

#211 Render only selected item breadcrumbs
  components/menu-breadcrumbs-items-loop.tpl
  components/menu-breadcrumbs.tpl
Labels: bug
